# Generated by Django 4.0.4 on 2022-07-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=24)),
                ('Product_amount', models.PositiveIntegerField()),
                ('Product_price', models.PositiveIntegerField()),
                ('Product_detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_Name', models.CharField(max_length=254)),
                ('Seller_Contact', models.CharField(max_length=11)),
                ('Address', models.CharField(max_length=254)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('CustomerPackageType', models.CharField(choices=[('inihaw', 'inihaw package'), ('classic', 'classic package'), ('fried', 'fried package'), ('other', 'other package')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_Rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('Review_Comment', models.TextField(blank=True)),
                ('Review_Suggestion', models.TextField(blank=True)),
                ('Product_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.sell')),
                ('Seller_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Date', models.DateField()),
                ('Order_Price', models.PositiveIntegerField(blank=True)),
                ('Order_Detail', models.TextField(blank=True)),
                ('Order_Status', models.TextField(choices=[('delivered', 'delivered'), ('for pickup', 'for pickup'), ('done', 'done')], default='for pickup')),
                ('Custumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.seller')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.sell')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delivery_Address', models.TextField(blank=True)),
                ('Delivery_Price', models.PositiveIntegerField(blank=True)),
                ('Delivery_Date', models.DateField()),
                ('Order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.order')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.sell')),
                ('Seller_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ilano_app.seller')),
            ],
        ),
    ]
